all:
  vars:
    edgeproxy_tld: olsson.me
  hosts:
    nashi.olsson.me:
      edgeproxy_domains:
        plex:
          backend: 'plex'
          port: '32400'
        sonarr:
          backend: 'sonarr'
          port: '8989'
        radarr:
          backend: 'radarr'
          port: '7878'
        nzbget:
          backend: 'nzbget'
          port: '6789'
        deluge:
          backend: 'deluge.olsson.me'
          port: '8112'
