---

- name: 'Install packages'
  package:
    name: '{{ item }}'
  with_items:
    - docker

- name: 'Setting up docker config'
  template: 
    src: 'etc-default-docker.j2'
    dest: '/etc/default/docker'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart docker'
  become: yes

- name: 'Configuring logrotate'
  template:
    src: 'etc-logrotate.d-docker.j2'
    dest: '/etc/logrotate.d/docker'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: yes

- name: 'Install docker-compose'
  include_tasks: 'docker-compose.yml'
  when: with_docker_compose

- meta: flush_handlers

- name: 'docker is {{ docker_state }}'
  systemd:
    name: 'docker'
    state: '{{ docker_state }}'
    enabled: '{{ ( docker_state == "started") | bool }}'


