- hosts: all
  become: True
  tasks:

### Base packages and settings

  - name: 'Install packages'
    package:
      name: '{{ item }}'
    with_items:
      - docker

  - name: 'Enable services'
    service:
      name: '{{ item }}'
      state: 'started'
      enabled: yes
    with_items:
      - 'docker'
   
