- hosts: all
  become: True
  tasks:

### Base packages and settings

  - name: 'Install packages'
    package:
      name: '{{ item }}'
    with_items:
      - 'origin-clients'
      - 'docker'

  - name: 'Create directory /etc/containers'
    file:
      name: '/etc/containers'
      state: 'directory'
      owner: 'root'
      group: 'root'
      mode: '0755'
  - name: 'Set up docker config'
    template:
      src: 'etc-containers-registries.conf.j2'
      dest: '/etc/containers/registries.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
    notify: 'restart docker'

  - name: 'Create directory /srv/openshift'
    file:
      name: '/srv/openshift'
      state: 'directory'
      owner: 'root'
      group: 'root'
      mode: '0755'
  - name: 'Set up openshift service'
    template:
      src: 'etc-systemd-system-openshift.service.j2'
      dest: '/etc/systemd/system/openshift.service'
      owner: 'root'
      group: 'root'
      mode: '0644'
    notify: 
      - 'reload systemd'
      - 'restart openshift'

### Flush before post install tasks
  - meta: flush_handlers

### Post Install

  - name: 'Enable services'
    service:
      name: '{{ item }}'
      state: 'started'
      enabled: yes
    with_items:
      - 'docker'
      - 'openshift'

  handlers:
    - name: 'reload systemd'
      command: 'systemctl daemon-reload'
    - name: 'restart docker'
      service:
        name: 'docker'
        state: 'restarted'
    - name: 'restart openshift'
      service:
        name: 'openshift'
        state: 'restarted'
